---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "team-video.fullname" . }}-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.app.name }}.{{ .Values.app.domain }}`)
      kind: Rule
      priority: 100
      services:
        - name: {{ include "team-video.fullname" . }}-web
          port: 80
  tls:
    certResolver: default
