apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team-nextcloud.fullname" . }}-secret
type: Opaque
stringData:
  password: {{ .Values.database.password }}
  rootpassword: {{ .Values.database.root_password }}