apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "team-chat.fullname" . }}-rc-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.storage.limits.data }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "team-chat.fullname" . }}-rc-tmp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "team-chat.fullname" . }}-mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.storage.limits.database }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "team-chat.fullname" . }}-mongo-backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.storage.limits.database }}
---